total_private_domains: unlimited
total_reserved_route_ports: unlimited
total_service_keys: unlimited
app_instance_limit: unlimited
app_task_limit: unlimited
memory-limit: 4G
instance-memory-limit: unlimited
total-routes: unlimited
total-services: unlimited
paid-service-plans-allowed: false
