enabled: false
ldapHost: ""
ldapPort: 0
use_tls: false
bindDN: ""
userSearchBase: ""
userNameAttribute: ""
userMailAttribute: ""
userObjectClass: ""
groupSearchBase: ""
groupAttribute: ""
groupObjectClass: ""
origin: azure-ad
insecure_skip_verify: ""
ca_cert: ""
useIDForSAMLUser: false
